version: 0.2
phases:
  install:
    runtime-versions:
      android: 29
      java: corretto8
      nodejs: 12
    commands:
      - npm install
   build:
    commands:
      - npm i --save-dev @react-native-community/cli 
      - cd android
      - ./gradlew clean
      - ./gradlew assembleRelease
artifacts:
  files:
    - '**/*.apk'
  
